"""
Default recipe database — 30 recipes across 7 brands.
Loaded on first run if no recipes.json exists.
"""

DEFAULT_RECIPES = {
    "Ripe Liquid Gold SS": {
        "yield": 150, "format": "SS-876ML", "special_instructions": [],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Liquid Gold FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Keep skimmed chicken fat from the kettle, strain into a squeeze bottle, and use as a finisher."],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"],
        "add_to_jar": ["1 Squirt (1tbsp) Chicken Fat"],
    },
    "Ripe Grass-Fed Beef SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Add roasted bones to water by themselves and skim scum as water heats up, prior to reaching a heavy boil (skim 2-3 times), then add remaining ingredients.","Sear tomato paste in a frying pan with 1 tbsp of tallow until caramelized. Add directly to the kettle."],
        "kettle_overnight": ["150L Water","60kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","600g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","1/2x Bunch Fresh Sage","1/2x Bunch Fresh Rosemary","1/2x Bunch Fresh Parsley","1/2x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Grass-Fed Beef FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Add roasted bones to water by themselves and skim scum as water heats up, prior to reaching a heavy boil (skim 2-3 times), then add remaining ingredients.","Sear tomato paste in a frying pan with 1 tbsp of tallow until caramelized. Add directly to the kettle."],
        "kettle_overnight": ["150L Water","60kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","600g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","1/2x Bunch Fresh Sage","1/2x Bunch Fresh Rosemary","1/2x Bunch Fresh Parsley","1/2x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Beef Basil Rose SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Add roasted bones to water by themselves and skim as water heats up, prior to reaching a heavy boil (skim 2-3 times to remove scum), then add remaining ingredients.","Sear tomato paste in a frying pan with 1 tbsp of tallow until caramelized. Add directly to the kettle."],
        "kettle_overnight": ["150L Water","50kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","600g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","250g Rose Petals","1x Bunch Fresh Sage","1x Bunch Fresh Rosemary","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": ["10x Bunch Fresh Basil (30 min simmer)"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Beef Basil Rose FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Add roasted bones to water by themselves and skim as water heats up, prior to reaching a heavy boil (skim 2-3 times to remove scum), then add remaining ingredients.","Sear tomato paste in a frying pan with 1 tbsp of tallow until caramelized. Add directly to the kettle."],
        "kettle_overnight": ["150L Water","50kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","600g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","250g Rose Petals","1x Bunch Fresh Sage","1x Bunch Fresh Rosemary","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": ["10x Bunch Fresh Basil (30 min simmer)"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Chicken Confit Garlic SS": {
        "yield": 150, "format": "SS-876ML", "special_instructions": [],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","2 x 400g Raw Garlic","2 x 400g Confit Garlic Adjunct","80g Black Peppercorn","20g Bay Leaf"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Spicy Chicken Ferm. Lemongrass SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Heat adjunct for 30 min in the kettle before straining."],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Dried Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme","2 x 900g Fermented Lemongrass Adjunct","3600g Fresh Chili Pepper"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt","2ml per Liter Lemon Juice"], "add_to_jar": [],
    },
    "Ripe Fermented Garlic Ginger SS": {
        "yield": 150, "format": "SS-876ML", "special_instructions": [],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme","2 x 1200g Fermented Garlic Ginger Adjunct"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt","2ml per Liter Ginger Juice"], "add_to_jar": [],
    },
    "Ripe Fermented Garlic Ginger FZ": {
        "yield": 190, "format": "FZ-750ML", "special_instructions": [],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme","2 x 1200g Fermented Garlic Ginger Adjunct"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt","2ml per Liter Ginger Juice"], "add_to_jar": [],
    },
    "Ripe Vegan Mushroom SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["This recipe uses COCONUT OIL to coat mushrooms.","Halve all fresh mushrooms and toss in coconut oil. Spread and roast on a sheet pan with a raised grate. Roast on Mushroom Setting."],
        "kettle_overnight": ["150L Water","20lbs Fresh, White Mushrooms","15lbs Fresh, Shiitake Mushrooms","4kg Onion","4kg Carrot","4kg Celery","400g Raw Garlic","2.4L Coconut Milk","400g Ginger Root","80g Turmeric Root","400g Lemongrass","150g Fresh Chili Pepper","20g Chaga Chunks","10g Reishi Powder","10g Cordyceps Powder","10g Maitake Powder"],
        "after_skim": ["160g (4 Bag) Kaffir Lime Leaf (30 min simmer)"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Ripe Vegan Mushroom FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["This recipe uses COCONUT OIL to coat mushrooms.","Halve all fresh mushrooms and toss in coconut oil. Spread and roast on a sheet pan with a raised grate. Roast on Mushroom Setting."],
        "kettle_overnight": ["150L Water","20lbs Fresh, White Mushrooms","15lbs Fresh, Shiitake Mushrooms","4kg Onion","4kg Carrot","4kg Celery","400g Raw Garlic","2.4L Coconut Milk","400g Ginger Root","80g Turmeric Root","400g Lemongrass","150g Fresh Chili Pepper","20g Chaga Chunks","10g Reishi Powder","10g Cordyceps Powder","10g Maitake Powder"],
        "after_skim": ["160g (4 Bag) Kaffir Lime Leaf (30 min simmer)"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "NE Chicken Lemon Ginger SS": {
        "yield": 150, "format": "SS-876ML", "special_instructions": [],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","8x Whole, Halved Lemons","80g Black Peppercorn","20g Bay Leaf"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Pink Salt","2ml per Liter Lemon Juice","1ml per Liter Ginger Juice"], "add_to_jar": [],
    },
    "NE Beef Rosemary Ginger SS": {
        "yield": 150, "format": "SS-876ML", "special_instructions": [],
        "kettle_overnight": ["150L Water","50kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Celery","80g Black Peppercorn","40g Dried Rosemary","2x Bunch Fresh Rosemary"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Pink Salt","5ml per Liter Ginger Juice"], "add_to_jar": [],
    },
    "NE Organic Mushroom Broth SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["This recipe uses OLIVE OIL to coat the mushrooms.","Halve all fresh mushrooms and toss in olive oil. Spread and roast on sheet pan with raised grate. Set oven to mushroom setting."],
        "kettle_overnight": ["150L Water","30lbs Halved, White Mushrooms","15lbs Halved, Lions Mane Mushrooms","Olive Oil","500g Dried Whole Maitake Mushrooms","4kg Onion","4kg Carrot","4kg Celery","400g Raw Garlic","1kg Shallots","80g Black Peppercorn","40g Cumin Seeds","40g Nutmeg","50g each Reishi, Turkey Tail, and Cordyceps Powder","10g Chaga Chunks","1x Full Bunch Fresh Rosemary","1x Full Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Pink Salt"], "add_to_jar": [],
    },
    "NE Chicken Turmeric Honey SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Heat honey on stovetop until caramelized, add directly to kettle."],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","1 x 750ml Turmeric Juice","4.5g per Liter Pink Salt","10ml per Liter Caramelized Honey"], "add_to_jar": [],
    },
    "TBS Beef With Mirepoix SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Use Butcher Shoppe Conventional Bones.","Skim this broth prior to reaching a heavy boil (skim 2-3 times to remove scum).","Sear tomato paste in frying pan with 1 tbsp of tallow until caramelized. Add directly to kettle."],
        "kettle_overnight": ["150L Water","40kg Roasted, Conventional Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","300g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme","1x Bunch Fresh Sage","1x Bunch Fresh Rosemary"],
        "after_skim": [],
        "finishing": ["4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "TBS Chicken With Mirepoix SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["GOLD LIDS"],
        "kettle_overnight": ["150L Water","50kg Roasted, Organic Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Thyme","1x Bunch Fresh Parsley"],
        "after_skim": ["1 x 750ml Turmeric Juice"],
        "finishing": ["4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "WM Plain Beef Bone Broth FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Roast Bones.","Skim the scum from this broth prior to reaching a heavy boil (skim 2-3 times).","Keep the leftover fat, store and label as: PREMIUM BEEF TALLOW, with date."],
        "kettle_overnight": ["150L Water","75kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","No Salt"], "add_to_jar": [],
    },
    "WM Beef Bone Broth SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Use Wild Meadow bones if possible, if not any grass-fed bones are ok.","This recipe uses TALLOW to coat the mushrooms.","Sear tomato paste in a frying pan with tallow until caramelized. Add directly to kettle.","Sear Lion's Mane mushrooms in a frying pan with tallow. Add directly to kettle."],
        "kettle_overnight": ["150L Water","75kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","4lbs Lion's Mane Mushrooms","300g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "WM Beef Bone Broth FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Use Wild Meadow bones if possible, if not any grass-fed bones are ok.","This recipe uses TALLOW to coat the mushrooms.","Sear tomato paste in a frying pan with tallow until caramelized. Add directly to kettle.","Sear Lion's Mane mushrooms in a frying pan with tallow. Add directly to kettle."],
        "kettle_overnight": ["150L Water","75kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","4lbs Lion's Mane Mushrooms","300g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "WM Chicken Bone Broth SS": {
        "yield": 190, "format": "SS-750ML",
        "special_instructions": ["Use Wild Meadow bones, if not enough, use any pasture raised bones.","If short on feet/heads, use standard pasture raised chicken bones to top up."],
        "kettle_overnight": ["150L Water","57kg Roasted, Pasture Raised Chicken Bones","~9kg Roasted, Pasture Raised Chicken Feet","~9kg Roasted, Pasture Raised Chicken Heads","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","200g Raw Garlic","200g Confit Garlic","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "WM Chicken Bone Broth FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Use Wild Meadow bones, if not enough, use any pasture raised bones.","If short on feet/heads, use standard pasture raised chicken bones to top up."],
        "kettle_overnight": ["150L Water","57kg Roasted, Pasture Raised Chicken Bones","9kg Roasted, Pasture Raised Chicken Feet","9kg Roasted, Pasture Raised Chicken Heads","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","200g Raw Garlic","200g Confit Garlic","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["4.5g per Liter Grey Salt"],
        "add_to_jar": ["1 Squirt Chicken Fat"],
    },
    "WM Beef Stock FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Use \"Meaty\" Wild Meadow Bones."],
        "kettle_overnight": ["150L Water","75kg Wild Meadows \"Meaty Bones\"","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery"],
        "after_skim": [],
        "finishing": ["4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "WM Turkey FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Defrost whole turkeys 3 days prior in the fridge.","Cut up and remove carcass, place in hotel pan, cover turkey in olive oil.","Set oven to preset: turkey, roast and add directly to broth.","Keep the turkey fat from the kettle, strain, and use that day to finish jars."],
        "kettle_overnight": ["140L Water (use less water than usual)","50kg Roasted, Organic Turkey Bones","2x Roasted, Whole Turkey (see special instructions)","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Dried Bay Leaf","1x Bunch Fresh Sage","1x Bunch Fresh Rosemary","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","3g per Liter Grey Salt"],
        "add_to_jar": ["1 Squirt (1 tbsp) Turkey Fat"],
    },
    "SF Fermented Lemongrass FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["This recipe is the same as RIPE but uses PASTURE RAISED.","Heat adjunct for 30 min in the kettle before straining."],
        "kettle_overnight": ["150L Water","50kg Roasted, Pasture Raised Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Dried Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme","2 x 900g Fermented Lemongrass Adjunct"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt","2ml per Liter Lemon Juice"], "add_to_jar": [],
    },
    "SF Fermented Garlic Ginger FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["This recipe is the same as RIPE but uses PASTURE RAISED.","Heat adjunct for 30 min in the kettle before straining."],
        "kettle_overnight": ["150L Water","50kg Roasted, Pasture Raised Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme","2 x 1200g Fermented Garlic Ginger Adjunct"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt","2ml per Liter Ginger Juice"], "add_to_jar": [],
    },
    "SF Beef Shallot Thyme FZ": {
        "yield": 190, "format": "FZ-750ML",
        "special_instructions": ["Add roasted bones to water by themselves and skim scum as water heats up, prior to reaching a heavy boil (skim 2-3 times), then add remaining ingredients.","Sear tomato paste in a frying pan with 1 tbsp of tallow until caramelized. Add directly to the kettle."],
        "kettle_overnight": ["150L Water","45kg Roasted, Grass-Fed Beef Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","400g Raw Garlic","400g Confit Shallot Adjunct","300g Tomato Paste","80g Black Peppercorn","20g Bay Leaf","1/2x Bunch Fresh Sage","1/2x Bunch Fresh Rosemary","1/2x Bunch Fresh Parsley","1/2x Bunch Fresh Thyme"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"],
        "add_to_jar": ["1 Squirt (1 tbsp) Confit Shallot Tallow"],
    },
    "EM Lamb Broth SS": {
        "yield": 190, "format": "SS-750ML",
        "special_instructions": ["Roast bones and ground lamb.","Dispose of Fat."],
        "kettle_overnight": ["150L Water","50kg Roasted, Lamb Bones","10kg Roasted, Ground Lamb Meat","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","800g Raw Garlic","8x Halved, Whole Lemons","80g Black Peppercorn","80g Dried Oregano","20g Bay Leaf","1x Bunch Fresh Rosemary","1x Bunch Fresh Parsley"],
        "after_skim": [],
        "finishing": ["Water — top kettle to 150L","4.5g per Liter Grey Salt"], "add_to_jar": [],
    },
    "Whispering Meadows Chicken Mirepoix SS": {
        "yield": 150, "format": "SS-876ML",
        "special_instructions": ["Keep skimmed chicken fat from the kettle, strain into a squeeze bottle, and use as a finisher."],
        "kettle_overnight": ["150L Water","50kg Roasted, Pasture Raised Chicken Bones","200g Apple Cider Vinegar","4kg Onion","2.5kg Carrot","2.5kg Celery","80g Black Peppercorn","20g Bay Leaf","1x Bunch Fresh Parsley","1x Bunch Fresh Thyme"],
        "after_skim": ["1 x 750ml Frozen Turmeric Juice"],
        "finishing": ["Water — top kettle to 150L","3g per Liter Grey Salt"], "add_to_jar": [],
    },
}
